compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
num_machines: 1
num_processes: 1
machine_rank: 0
gpu_ids: 0,
use_cpu: false
enable_cpu_affinity: false
main_training_function: main
rdzv_backend: static
same_network: true
